# A meta-package including PyRAF and any external IRAF-style packages that
# require it (and therefore don't belong in iraf-all).
#
# Currently this is not really useful, since the kepler package is broken.

about:
    home: http://www.stsci.edu/institute/software_hardware/pyraf
    license: various (see individual packages)
    summary: PyRAF and the external IRAF-style packages that require it
build:
    number: '0'
package:
    name: pyraf-all
    version: "1.0"
requirements:
    build:
    - iraf !=2.16.1,>=2.16.UR  # external pkgs here need the ".UR" build
    - python                   # needed just to get py2/3-specific builds
    - pyraf
    - pyraf.kepler # [py2k]
    run:
    - iraf !=2.16.1,>=2.16.UR  # should this be iraf-all, to get everything?
    - python
    - pyraf
    - pyraf.kepler # [py2k]    # the authors only support Py 2, as of May 2017

