package:
    name: gemini_calmgr
    version: "0.9.12"
source:
    svn_url: http://scisoft.gemini.edu/svn/FitsStorage/branches/GeminiCalMgr-0.9
    svn_rev: 3517
build:
    number: '0'
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: Local calibration manager for use with DRAGONS
requirements:
    build:
    - python
    - setuptools
    run:
    - python
    - astropy >=1.2.1
    - dragons >=2
    - sqlalchemy >=1.0

