{% set version = '1.1.24' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

package:
    name: gemini_calmgr
    version: {{ version }}
source:
    git_url: git@github.com:GeminiDRSoftware/GeminiCalMgr.git
    git_tag: {{ tag }}
build:
    number: {{ number }}
    noarch: python
    script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    license_file: LICENSE
    summary: Local calibration manager for use with DRAGONS
requirements:
    build:
    - python >=3.7
    - pip
    - setuptools
    run:
    - python >=3.7
    - dragons >=3.1.0
    - gemini_obs_db >=1.0
    - sqlalchemy >=1.3,<2.0.0a0  # code not yet updated for new v2 API

