package:
    name: gemini_calmgr
    version: "1.0.0.dev"
source:
    git_url: git@gitlab.gemini.edu:DRSoftware/FitsStorage.git
    git_tag: 2020-2.11  # host FITSStorage repo has its own versioning...
build:
    number: '0'
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: Local calibration manager for use with DRAGONS
requirements:
    build:
    - python
    - setuptools
    run:
    - python
    - astropy >=4.1
    - dragons >=3.0.0.dev
    - sqlalchemy >=1.3

