# This is not really an IRAF package per se, but is called "iraf.axe" because
# it's an add-on for STSDAS and the intention is to distribute a stand-alone
# version later as a separate package (presumably "axe").
about:
    home: http://axe-info.stsci.edu
    license: GPL
    summary: STScI/STECF aXe add-on for the STSDAS IRAF package
build:
    binary_relocation: True
    number: '0'
package:
    name: iraf.axe
    version: "2.6.2"
source:
    # The aXe 2.6 release is built from the 2.5 source, but with its version
    # updated to go with some changes to associated Python files in STSDAS.
    - url: http://astroconda-source:4440/aXeTZ-2.5.tar.gz
      folder: aXe
      patches:
      - ac.iraf.axe.patch  # patched to build against recent wcstools
    - url: http://astroconda-source:4440/gsl-1.9.tar.gz  # aXe needs old GSL
      folder: gsl
requirements:
    build:
    # is pkgconfig also needed here, as per Joe's email?
    - iraf !=2.16.1,>=2.16.UR  # IRAF is just used to determine install paths
    - iraf.stsdas              # just to install into; not a real build dep.
    - cfitsio >=3.35
    - wcstools >=3.8.4
    run:
    - iraf !=2.16.1,>=2.16.UR
    - iraf.stsdas >=3.18.3     # need this ver. of python files in "slitless" 
    - cfitsio >=3.35
    - wcstools >=3.8.4

