python:
  - 3.12
  - 3.13
  - 3.14

# Make sure GIL versions get picked up for 3.14+, as not all of our deps
# support free-threaded python yet:
python_abi:
  - "3.12.* *_cp312"
  - "3.13.* *_cp313"
  - "3.14.* *_cp314"

c_stdlib:
  - sysroot                       # [linux]
  - macosx_deployment_target      # [osx]

c_stdlib_version:
  - '2.28'                        # [linux]
  - '11.0'                        # [osx]

MACOSX_DEPLOYMENT_TARGET:
  - '11.0'

CONDA_BUILD_SYSROOT:
  - "/rtfperm/SDKs/MacOSX11.1.sdk"  # [osx]

zip_keys:
  - [python, python_abi]

