{% set version = '4.0.0' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

package:
    name: dragons
    version: {{ version }}
source:
    git_url: https://github.com/GeminiDRSoftware/DRAGONS.git
    git_tag: {{ tag }}
build:
    number: {{ number }}
    binary_relocation: True
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    license_file:
      - LICENSE
      - extern_licenses/
    summary: The main DRAGONS package for processing Gemini data
requirements:
    build:
    - python
    - pip
    - setuptools
    - cython >=0.29
    - docutils >=0.15
    - sphinx >=1.2.2
    - sphinx_rtd_theme >=0.3.0
    run:
    - python
    - asdf >=2.15
    - astropy >=6.0,!=6.1.5,!=6.1.6  # v6.1.5 sigma clip problem 17401
    - astroquery >=0.4
    - astroscrappy >=1.1
    - bokeh >=3.0
    - bottleneck >=1.2          # opt but needed for astropy.stats performance
    - fits_storage >=3.4.0
    - fitsverify >=4.17
    - future >=0.17
    - gwcs >=0.19,<=0.22.1
    - holoviews >=1.20
    - jinja2 >=3.0
    - jsonschema >=3.0
    - matplotlib >=3.7
    - numpy >=1.24,<2.0.0a0
    - pandas >=2.0
    - psutil >=5.6
    - pyerfa >=1.7
  # - pytest >=5.2              # also need pytest_dragons etc. for self test
    - python-dateutil >=2.8
    - requests >=2.22
    - scikit-image >=0.21
    - scipy >=1.11
    - sextractor >=2.8.6
    - specutils >=1.10
    - sqlalchemy >=2.0
    - tornado >=6.3
    run_constrained:
    - ds9 >=8.0
