build:
    binary_relocation: True
    number: '2'
package:
    name: dragons
    version: "3.0.0"
source:
    git_url: git@github.com:GeminiDRSoftware/DRAGONS.git
    git_tag: v3.0.0
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: The main DRAGONS package for processing Gemini data
requirements:
    # Most of the dependencies besides python are not actually needed to
    # "build" dragons, but including them here ensures that they get built
    # and therefore that the package is installable.
    build:
    - python
    - setuptools
    - gemini-anaconda=2020.11.g0  # Workaround for building on CentOS 6
    - asdf >=2.7
    - astropy >=4.2
    - astroquery >=0.4
    - bokeh >=2.2
    - bottleneck >=1.2
    - cython >=0.29
    - disco_stu >=1.3.7
    - docutils >=0.15
    - future >=0.17
    - gwcs >=0.14
    - imexam >=0.8
    - jsonschema >=3.0
    - matplotlib >=3.1
    - numpy >=1.17
    - psutil >=5.6
    - pyerfa >=1.7
    - pytest >=5.2
    - python-dateutil >=2.5.3
    - requests >=2.22
    - scipy >=1.3
    - scikit-image >=0.15
    - specutils >=1.1
    - sphinx >=1.2.2
    - sphinx_rtd_theme >=0.3.0
    - sqlalchemy >=1.3
    - fitsverify >=4.17
    - sextractor >=2.8.6
    run:
    - python
    - asdf >=2.7
    - astropy >=4.2
    - astroquery >=0.4
    - bokeh >=2.2
    - bottleneck >=1.2          # opt but needed for astropy.stats performance
    - disco_stu >=1.3.7
    - future >=0.17
    - gemini_calmgr >=1.0.0
    - gwcs >=0.14
    - imexam >=0.8              # make this optional for SQ
    - jsonschema >=3.0
    - matplotlib >=3.1
    - numpy >=1.17
    - psutil >=5.6
    - pyerfa >=1.7
    - pytest >=5.2              # could be opt but allow self-test; incomplete?
    - python-dateutil >=2.5.3
    - requests >=2.22
    - scipy >=1.3
    - scikit-image >=0.15
    - specutils >=1.1
    - sqlalchemy >=1.3
    - fitsverify >=4.17
    - sextractor >=2.8.6
    run_constrained:
    - ds9 >=8.0
