build:
    binary_relocation: True
    number: '1'
package:
    name: dragons
    version: "2.1.1"
source:
    git_url: https://github.com/GeminiDRSoftware/DRAGONS.git
    git_tag: v2.1.1
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: The main DRAGONS package for processing Gemini data
requirements:
    # Most of the dependencies besides python are not actually needed to
    # "build" dragons, but including them here ensures that they get built
    # and therefore that the package is installable.
    build:
    - python
    - setuptools
    - astropy >=2
    - astroquery >=0.3.5
    - configparser >=3.5        # [py2k]
    - cython >=0.24.1
    - disco_stu >=1.3.7
    - future >=0.16.0
    - futures >=3.2             # [py2k]  # for FITS store metrics
    - matplotlib >=1.4.2
    - numpy >=1.9.1
    - psutil >=5.4
    - pytest >=2.9.2
    - python-dateutil >=2.5.3
    - requests >=2.11.1
    - scipy >=0.15.1
    - scikit-image >=0.10.1
    - sphinx >=1.2.2
    - sphinx_rtd_theme >=0.3.0
    - sqlalchemy >=1.0
    - fitsverify >=4.17
    - sextractor >=2.8.6
    run:
    - python
    - astropy >=2
    - astroquery >=0.3.5
    - configparser >=3.5        # [py2k]
    - disco_stu >=1.3.7
    - future >=0.16.0
    - futures >=3.2             # [py2k]  # for FITS store metrics
    - gemini_calmgr >=0.9
    - matplotlib >=1.4.2
    - numpy >=1.9.1
    - psutil >=5.4
    - pytest >=2.9.2            # could be opt. but better allow self-test
    - python-dateutil >=2.5.3
    - requests >=2.11.1
    - scipy >=0.15.1
    - scikit-image >=0.10.1
    - sqlalchemy >=1.0
    - fitsverify >=4.17
    - sextractor >=2.8.6
    run_constrained:
    - ds9 >=8.0
