{% set name = 'pyraf' %}
{% set version = '2.1.10' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/pyraf
    license: BSD
    summary: pyraf
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - d2to1
    - astropy >=1.1
    - ipython
    - matplotlib
    - pyobjc-core ==3.0.4 [osx and py27]
    - pyobjc-framework-cocoa ==3.0.4 [osx and py27]
    - pyobjc-framework-quartz ==3.0.4 [osx and py27]
    - pyobjc-core ==3.1.1 [osx and py3k]
    - pyobjc-framework-cocoa ==3.1.1 [osx and py3k]
    - pyobjc-framework-quartz ==3.1.1 [osx and py3k]
    - stsci.tools
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.1
    - ipython
    - matplotlib
    - pyobjc-core ==3.0.4 [osx and py27]
    - pyobjc-framework-cocoa ==3.0.4 [osx and py27]
    - pyobjc-framework-quartz ==3.0.4 [osx and py27]
    - pyobjc-core ==3.1.1 [osx and py3k]
    - pyobjc-framework-cocoa ==3.1.1 [osx and py3k]
    - pyobjc-framework-quartz ==3.1.1 [osx and py3k]
    - stsci.tools
    - numpy x.x
    - python x.x
source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/pyraf
test:
    commands:
    - pyraf --help
