{% set name = 'pyraf' %}
{% set version = '2.2.1' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/iraf-community/{{ name }}
    license: BSD
    summary: |
        Provides a Pythonic interface to IRAF

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - configobj >=5
    - ipython
    - matplotlib
    - pyobjc-core >=3.0.4 [osx]
    - pyobjc-framework-cocoa >=3.0.4 [osx]
    - pyobjc-framework-quartz >=3.0.4 [osx]
    - setuptools
    - setuptools_scm
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - configobj >=5
    - ipython
    - matplotlib
    - pyobjc-core >=3.0.4 [osx]
    - pyobjc-framework-cocoa >=3.0.4 [osx]
    - pyobjc-framework-quartz >=3.0.4 [osx]
    - numpy
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/iraf-community/{{ name }}.git

test:
    commands:
    - pyraf --help
