{% set name = 'pyraf' %}
{% set version = '2.2.1' %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
    home: https://github.com/iraf-community/{{ name }}
    license: BSD
    summary: |
        Provides a Pythonic interface to IRAF

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    host:
    - python
    - astropy >=1.1
    - configobj >=5
    - ipython
    # - libffi >=3.3,<3.4a0 [osx]
    - matplotlib
    - numpy
    - pyobjc-core >=7.2,<7.3 [osx]
    - pyobjc-framework-cocoa >=7.2,<7.3 [osx]
    - pyobjc-framework-quartz >=7.2,<7.3 [osx]
    - setuptools
    - setuptools_scm
    run:
    - python
    - astropy >=1.1
    - configobj >=5
    - ipython
    # This dependency is missing from pyobjc-core in conda-forge, resulting in
    # a broken objc unless the correct Python patch level is installed, but
    # adding it here caused other problems, including the old Astroconda pyraf
    # build (which is even more broken with conda-forge) being picked up with
    # the latest Python and cases of builds failing due to conda issue 11442.
    # - libffi >=3.3,<3.4a0 [osx]
    - matplotlib
    - numpy
    - pyobjc-core >=7.2,<7.3 [osx]
    - pyobjc-framework-cocoa >=7.2,<7.3 [osx]
    - pyobjc-framework-quartz >=7.2,<7.3 [osx]

source:
    git_tag: {{ tag }}
    git_url: https://github.com/iraf-community/{{ name }}.git

test:
    commands:
    - pyraf --help
