{% set name = 'pyraf' %}
{% set version = '2.1.11' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '2' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Provides a Pythonic interface to IRAF

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy >=1.1
    - ipython
    - matplotlib
    - pyobjc-core >=3.0.4 [osx]
    - pyobjc-framework-cocoa >=3.0.4 [osx]
    - pyobjc-framework-quartz >=3.0.4 [osx]
    - stsci.tools
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - ipython
    - matplotlib
    - pyobjc-core >=3.0.4 [osx]
    - pyobjc-framework-cocoa >=3.0.4 [osx]
    - pyobjc-framework-quartz >=3.0.4 [osx]
    - stsci.tools
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - pyraf --help
