{% set name = 'pyraf' %}
{% set version = '2.2.4' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/iraf-community/{{ name }}
    license: BSD
    summary: |
        Provides a Pythonic interface to IRAF

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - {{ compiler('c') }}
    host:
    - {{ stdlib('c') }}
    - python
    - python-gil  # [py>=313]
    - pip
    - setuptools
    - setuptools_scm
    - configobj >=5
    # Version spec needs checking, but should avoid previous libffi problem:
    - pyobjc-core >=8  # [osx]
    - pyobjc-framework-cocoa >=8  # [osx]
    - pyobjc-framework-quartz >=8  # [osx]
    - xorg-libx11  # [linux]
    - xorg-xorgproto  # [linux]
    run:
    - python
    - python-gil  # [py>=313]
  # - astropy >=1.1  # only used for testing
    - configobj >=5
    - ipython
    - matplotlib
    - numpy >=1.26
    - pyobjc-core >=8  # [osx]
    - pyobjc-framework-cocoa >=8  # [osx]
    - pyobjc-framework-quartz >=8  # [osx]
    - xorg-libx11  # [linux]

source:
    git_tag: {{ tag }}
    git_url: https://github.com/iraf-community/{{ name }}.git

test:
    commands:
    - pyraf --help
