about:
    home: https://github.com/jehturner/astroconda-utils
    license: BSD
    summary: Build and run time utilities for AstroConda
build:
    binary_relocation: True
    #detect_binary_files_with_prefix: False [osx]
    number: '0'
package:
    name: astroconda-utils
    version: "0.1"
source:
    git_url: https://github.com/jehturner/astroconda-utils.git
requirements:
    run:
    - iraf ==2.16_UR
    - pyraf

