about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    license_file: LICENSE
    summary: Gemini Distortion Correction and Stacking Utility (for GSAOI)
build:
    binary_relocation: True
    number: '0'
package:
    name: disco_stu
    version: "1.3.7"
source:
    # fn: disco_stu-1.3.7.tar.gz
    # url: http://www.gemini.edu/sciops/data/software/disco_stu-1.3.7.tar.gz
    git_url: git@gitlab.gemini.edu:DRSoftware/disco_stu.git
    git_tag: v1.3.7
requirements:
    build:
    - python x.x                # syntax needed to build for each python ver.
    - sphinx
    - texlive                   # (from astroconda-gemini-internal)
    run:
    - python x.x                # (OrderedDict & argparse require >=2.7)
    - numpy >=1.9               # (version tested, from the manual)
    - scipy >=0.14              # (to match the NumPy requirement)
    - astropy >=1.0,<4          # (from the manual, plus known incompat.)
    - sextractor >=2.8.6        # (from the manual)

