{% set name = 'sextractor' %}
{% set version = '2.19.5' %}

about:
    home: http://www.astromatic.net/download/{{ name }}
    license: GPL
    summary: |
        SExtractor is a program that builds a catalogue of objects from an astronomical image

build:
    number: '1' [linux]
    number: '0' [osx]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - atlas-generic [linux]
    - autoconf [osx]
    - m4 [osx]
    - fftw
    - pkgconfig
    run:
    - atlas-generic [linux]
    - fftw

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: http://www.astromatic.net/download/sextractor/{{ name }}-{{ version }}.tar.gz
