package:
    name: gemini
    version: 2.1
build:
    number: '0'
    noarch: generic
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD & (for Gemini IRAF) non-commercial use
    summary: Collection of Gemini data reduction packages (meta-package)
requirements:
    # Let these versions float so users can "update" them individually, but
    # avoid picking up internal versions from the gemini channel (the matching
    # logic considers numbers greater than letters).
    run:
    - iraf.gemini >1
    - dragons >=3.1   # disco-stu has been moved into dragons 3.1
