about:
    home: http://iraf.noao.edu
    license: MIT
    summary: NOAO Image Reduction and Analysis Facility
build:
    #binary_relocation: False [osx]
    #detect_binary_files_with_prefix: False [osx]
    number: '0'
package:
    name: iraf
    version: 2.16.1
source:
    git_url: /eng/ssb/jhunk/git-repos/iraf.git
