about:
    home: http://iraf.noao.edu
    license: MIT (and third-party licenses)
    summary: NOAO Image Reduction and Analysis Facility
build:
    binary_relocation: False  # [osx]
    detect_binary_files_with_prefix: False
    # (if binary relocation is problematic, add "ignore_prefix_files" below)
    rpaths:
    - lib32/
    number: '0'
package:
    name: iraf
    version: "2.16.UR.1"
requirements:
    build:
    - iraf-os-libs  # [linux]
    run:
    - iraf-os-libs  # [linux]
source:
    # You must upload your ssh key to github to check out this private repo:
    #git_url: git@github.com:spacetelescope/iraf.git
    git_url: https://github.com/spacetelescope/iraf.git
    git_tag: 2.16.UR.1

