about:
    home: http://iraf.noao.edu
    license: MIT (and third-party licenses)
    summary: NOAO Image Reduction and Analysis Facility
build:
    binary_relocation: False  # [osx]
    detect_binary_files_with_prefix: False
    # (if binary relocation is problematic, add "ignore_prefix_files" below)
    rpaths:
    - lib32/
    number: '0'
package:
    name: iraf
    version: "2.16.UR"
requirements:
    build:
    - iraf-os-libs  # [linux]
    run:
    - iraf-os-libs  # [linux]
source:
    svn_url: https://aeon.stsci.edu/ssb/svn/u-rel/iraf-2.16/trunk

