about:
    home: http://iraf.noao.edu
    license: MIT (and third-party licenses)
    summary: Core NOAO IRAF and X11IRAF meta-package (including help)
build:
    number: '0'
package:
    name: iraf
    version: "2.16.UR"
requirements:
    # IRAF is a special case where we hard-wire the version numbers so that the
    # meta-package seen by users can have a recognizable version number and
    # provide the corresponding IRAF version (whereas in general, meta packages
    # will provide the latest package versions at install time, to allow
    # updating component packages easily etc.).
    build:
    - iraf-core ==2.16.UR
    - iraf-help ==2.16.UR
    - iraf-x11  ==2.0
    run:
    - iraf-core ==2.16.UR    # (also pulls in iraf-os-libs)
    - iraf-help ==2.16.UR
    - iraf-x11  ==2.0

