about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: Gemini Distortion Correction and Stacking Utility (for GSAOI)
build:
    binary_relocation: True
    #detect_binary_files_with_prefix: False [osx]
    number: '0'
package:
    name: gemini.disco_stu
    version: "1.3.1"
source:
    fn: disco_stu-1.3.1.tar.gz
    url: http://www.gemini.edu/sciops/data/software/disco_stu-1.3.1.tar.gz
requirements:
    build:
    - python x.x                # syntax needed to force 2.7 builds...
    run:
    - python >=2.7              # (uses OrderedDict, argparse)
    - numpy >=1.9               # (version tested, from the manual)
    - scipy >=0.14              # (to match the NumPy requirement)
    - astropy >=1.0             # (from the manual)
    - sextractor >=2.8.6        # (from the manual)

