c_compiler:                         # [linux]
    - gcc                           # [linux]
c_compiler_version:                 # [linux]
    - '13'                          # [linux]
c_stdlib:                           # [linux]
    - sysroot                       # [linux]
c_stdlib_version:                   # [linux]
    - '2.17'                        # [linux]
cxx_compiler:                       # [linux]
    - gxx                           # [linux]
cxx_compiler_version:               # [linux]
    - '13'                          # [linux]
target_platform:                    # [linux]
    - linux-64                      # [linux]

MACOSX_DEPLOYMENT_TARGET:           # [osx]
    - '10.13'                       # [osx]
MACOSX_SDK_VERSION:                 # [osx]
    - '10.13'                       # [osx]
c_compiler:                         # [osx]
    - clang                         # [osx]
c_compiler_version:                 # [osx]
    - '18'                          # [osx]
c_stdlib:                           # [osx]
    - macosx_deployment_target      # [osx]
c_stdlib_version:                   # [osx]
    - '10.13'                       # [osx]
cxx_compiler:                       # [osx]
    - clangxx                       # [osx]
cxx_compiler_version:               # [osx]
    - '18'                          # [osx]
target_platform:                    # [osx]
    - osx-64                        # [osx]

# # These aren't critical, but allow installation with not-quite-the-latest
# # stack at the time of building 8.6. But, actually, that caused problems
# # linking with libxft, due to a change in fontconfig's expat dependency.
# expat:
#     - '2.6.1'
# libiconv:
#     - '1.17'
# liblzma_devel:
#     - '5.6.3'
# libxml2:
#     - '2.12.7'
# libxslt:
#     - '1.1.39'
# xorg_libx11:
#     - '1.8.10'
# xorg_libxcursor:                    # [linux]
#     - '1.2.0'                       # [linux]
# xorg_libxfixes:                     # [linux]
#     - '6.0.0'                       # [linux]
# xorg_libxft:
#     - '2.3.8'
# zlib:
#     - '1.3.1'

