{% set name = 'ds9' %}
{% set version = '8.6' %}
{% set number = '1' %}

about:
    home: http://ds9.si.edu/download/source/
    license: GPL,LGPL,BSD
    summary: |
        SAOImage DS9 is an astronomical imaging and data visualization application

build:
    number: {{ number }}
    ignore_run_exports:
    - libexpat # }
    - libxml2  # } these are only *direct* deps at build time
    - libxslt  # }

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - {{ compiler('c') }}
      - {{ stdlib('c') }}
      - {{ compiler('cxx') }}
      - autoconf
      - m4
      - pkg-config
    host:
      - expat
      - fontconfig
      - freetype
      - libiconv
      - libxml2-devel
      - libxslt
      - xorg-libx11
      - xorg-libxft
      - xorg-xorgproto
      - zlib
    run:
      - xorg-libxcursor   # [linux]
      - xorg-libxfixes    # [linux]

source:
    fn: {{ name }}.{{ version }}.tar.gz
    url: https://github.com/SAOImageDS9/SAOImageDS9/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 41a3ea004a691b73fdebdfdd6b821d2620885b27ec3d157f7a79ae941187d843
    patches:
      - configure.patch
      - Makefile.in.patch
      - make.include.patch
      - libtiff_configure.patch
      - pngpriv.h.patch
      - zutil.h.patch
