{% set name = 'ds9' %}
{% set version = '7.5' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home: http://ds9.si.edu/download/source/
    license: GPL,LGPL,BSD
    summary: |
        SAOImage DS9 is an astronomical imaging and data visualization application

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - gcc >=4.6 [osx]

source:
    fn: {{ name }}.{{ version }}.tar.gz
    url: http://ds9.si.edu/download/source/{{ name }}.{{ version }}.tar.gz
    md5: 5684be5f6123f3d0426ea3db46466cb4
