{% set name = 'ds9' %}
{% set version = '7.6' %}
{% set number = '0' %}

about:
    home: http://ds9.si.edu/download/source/
    license: GPL,LGPL,BSD
    summary: |
        SAOImage DS9 is an astronomical imaging and data visualization application

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - gcc >=4.6 [osx]

source:
    fn: {{ name }}.{{ version }}.tar.gz
    url: http://ds9.si.edu/download/source/{{ name }}.{{ version }}.tar.gz
    md5: b700dd815fe1f7fa93e3e3bba1132ca7
