# Note that this package is NOT fully working in AstroConda. It has been
# patched to use astropy.io.fits (etc.) but the functionality has not been
# tested properly. The "analysis" & "transit" modules used by lightcurve.py &
# keptransit.py (via ma02.py) are missing from both AstroConda and Ureka.
# The deprecated scipy.optimize.anneal in keptransit.py needs replacing with
# optimize.basinhopping (possibly amongst other API changes).

about:
    home: http://iraf.noao.edu/
    license: US government notice, BSD, attribution requirement
    summary: KEPLER package for PyRAF
build:
    binary_relocation: False
    number: '0'
    # These must be copied from astroconda-iraf-helpers, since conda disallows
    # the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: pyraf.kepler
    version: "2.6.2"
source:
    fn: PyKE_2.6.2.tar
    url: http://astroconda-source:4440/PyKE_2.6.2.tar
    patches:
    - ac.iraf.kepler.patch  # converts pyfits imports to io.fits for AstroConda
requirements:
    build:
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR
    run:
    - iraf !=2.16.1,>=2.16.UR
    - pyraf
    - astropy
    - matplotlib
    - numpy
    - scipy
    - mdp

